#
# Makefile for the accelerometer drivers.
#

# Each configuration option enables a list of files.



obj-$(CONFIG_ACCELEROMETER_ADXL345)	+= gsdev.o
obj-$(CONFIG_ACCELEROMETER_ST_L1S35DE)	+= gs_st.o
obj-$(CONFIG_ACCELEROMETER_MMA7455L)	+= gs_freescale.o
obj-$(CONFIG_ACCELEROMETER_ADI_ADXL346)	+= gs_adi346.o
obj-$(CONFIG_ACCELEROMETER_ST_LIS3XH)	+= gs_st_lis3xh.o
obj-$(CONFIG_ACCELEROMETER_MMA8452)	+= gs_mma8452.o
obj-$(CONFIG_ACCELEROMETER_BOSCH_BMA250)	+= gs_bosch.o

